### ISSUE TITLE
Parent definition

### ISSUE THREAD

**Issue by boeh-da** [DLR-SL/CPACS#415]
There needs to be a clear distinction what the parent definition in CPACS stands for. 

Currently, we use it to define a geometrical relation of components. E.g. the vtp has the fuselage as parent. If the fuselage is shifted backwards this implies that the vtp will be shifted backwards as well. However, it is not clear whether the fuselage and the vtp are connected from the above example...

**Comment by MarAlder** [comment]
Closed by #733 (I hope... If not, please reopen).
