### ISSUE TITLE
How to handle empty or non-existent values

### ISSUE THREAD

**Issue by boeh-da** [DLR-SL/CPACS#423]
It is possible that in a performance map not all entries should be filled. Either because the calculation becomes to costly or for reasons of physical models, i.e., the node cannot be computed.

During the Entwicklertreffen these issues should be discussed. How do we handle empty slots, like Nan or else. How can Tixi interpret this data.

**Comment by codingpoets** [comment]
This issue can be fixed using non structured points for the aeroPerformanceMap as suggested by #532.

**Comment by MarAlder** [comment]
This issue is addressed by #505 (see [report](https://www.cpacs.de/reports/report_APM.pdf)).
