### ISSUE TITLE
aeroToolPerformanceMapType contains duplicate definitions

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-SL/CPACS#477]
`aeroToolPerformanceMapType` uses a choice with different sets of element definitions.
However, `positiveQuasiSteadyRotation` and `negativeQuasiSteadyRotation` are defined twice.

We could pull them outside the choice, but this would require a sequence, which would prescribe an order.

Alternative would be to remove the choice altogether and make all children optional, but this could taint the intended exclusive semantics of `controlSurfaceUID` vs. `controlSurfaces`.

**Comment by ArneBachmann** [comment]
Using a common supertype with the `...QuasiSteadyRotation` for both choice options with two further (probably anonymous) type extensions as choices, but inheritance always introduces a sequence, I read somewhere (even if subtype uses ` xsd:all`). If not, this would be the correct modelling approach.

**Comment by codingpoets** [comment]
With the removal of toolspecifics this issue will be resolved from the perspective of the CPACS schema.

**Comment by MarAlder** [comment]
closed by #611
