### ISSUE TITLE
Use xs:normalizedString instead of xs:string where needed

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-SL/CPACS#482]
Because it removes line feeds, carriage returns, and tab characters when parsed by the XML processor.
https://www.w3schools.com/xml/schema_dtypes_string.asp

Even xs:token might be meaningful in some places (also collapses multiple whitespaces and removes leading/trailing ws).

**Comment by CLiersch** [comment]
Where exactly do you want to use normalized strings instead of normal strings? Are there any use cases where it is necessary to prohibit <CR> etc.? In some cases, string enumerations are used (e.g. for Switches). I think, these have to remain as strings.

**Comment by ArneBachmann** [comment]
This was just a measure to make CPACS documents safer. Especially for enum values we wouldn't want newlines, tabs or other invisible characters contained.
However, this [link](http://www.xmlplease.com/normalized) explains that the `xsd:normalizedString` and `xsd:token` only show the intent, and are currently not validated even by official XSD parsers.

So the situation is that we don't get an actual benefit unless our tools help enforce the stricter definition of these types (I could do that in my tools, if needed).
Nevertheless in many cases I would prefer a restriction to `xsd:token` over `xsd:string` as it corresponds with what programs would do with these strings anyway (strip non-printable characters, and probably leading and trailing white spaces as well).

**Comment by CLiersch** [comment]
I could imagine that such a restriction can be useful in some cases (e.g. links to UIDs, probably &lt;name&gt; nodes, ...). Maybe for &lt;description&gt; nodes we should stay with a string in order to Permit some text formatting. Regarding enumerations I first thought they would be restricted to string types, but I now guess, they can be used in Tokens and normalizedStrings, as well. Is that correct? Anyway, I thought enumerations would not permit additional whitespaces etc. either.

**Comment by MarAlder** [comment]
As far as I understand` xsd:token` (based on `xsd:normalizedString`) is not a restriction, i.e. validation is successful even though spaces and tabs are used. I tried with Eclipse and lxml. The XML processor just strips the string before passing it to the validator. The actual benefits of this are not yet quite clear to me, but under these conditions, the element may currently have little significance for our way of working with CPACS. 

I will keep the possibility in mind and close the issue for now, as it is not acute at the moment. If it is needed in a suitable place, we can think again about the introduction and reopen the issue.
