### ISSUE TITLE
Remove toolspecific node and replace by toolspecific namespaces

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-SL/CPACS#484]
I generated a list of types that could be removed from CPACS entirely and live in their own namespaces, cf. attached text file.
[removables.txt](https://github.com/DLR-LY/CPACS/files/831304/removables.txt)

I also assembled a reduced schema to show the actual reduction when leaving out the toolspecific node, but GitHub doesn't allow me to upload the XSD, not even as a ZIP file.
The file size reduction is from 1443kb to 1120kB, which is about 20%.
The number of types is reduced from ~935 by ~242 type definitions (about 25%), which are only relevant to specific tools and might be seen to clutter the standard.

**Comment by bernhardmgruber** [comment]
Referring back to #448, especially to the initial proposal of @sdeinert, we at RISC Software would also prefer to have a xsd:any content inside ``<toolspecific>``, as we develop custom extensions to CPACS. For these extensions we develop own schema files and reference them from the XML elements inside the ``<toolspecific>`` node, resetting the namespace inside our own elements.

An example may look like this:
```
<cpacs xmlns:xsi="..." xsi:noNamespaceSchemaLocation="...">
  ... <!-- standard content -->
  <toolspecific>
    ... <!-- "standard" DLR toolspecific elements -->
    <myExtension xmlns="...myExtensionSchema...">
      <!-- my extension content, default namespace in here is now my extension -->
    </myExtension>
    <ext:myOtherExtension xmlns:ext="...myOtherExtensionSchema...">
      <!-- my other extension content, ext namespace in here is now my other extension -->
    </ext:myOtherExtension>
  </toolspecific>
</cpacs>
```

AFAIK this is not possible with XML schemas, as we cannot mix xsd:all and xsd:any. A possible solution would be to add a subelement to ``<toolspecific>`` allowing any content (for third-party extensions). However, we would like to have the content of <toolspecific> to be any, and, as suggested by @ArneBachmann, create an additional schema file for all DLR toolspecific elements.

Do you see any other way of solving the problem of third-party extensions?
We think it is the easiest to change ``<toolspecific>`` to have any content.

**Comment by ArneBachmann** [comment]
Is it technically necessary to define a xsd:any when only using different namespaces as children? I would assume any schema to only validate its own namespace and never reference other namespaces, while elements of other namespaces may be placed anywhere throughout the file, only referenced in the XML file's header xmlns attributes? But I'm not an XML expert.

**Comment by bernhardmgruber** [comment]
Thank you for your suggestion!

We have tested this now internally and can confirm that indeed a schema only validates elements of its own namespace. Therefore, if we add additional subelements unter \<toolspecific> and set namespaces accordingly (either explicitely with xmlns:ext="..." or resetting the default namespace with xmlns="..."), the XML file validates correctly against the CPACS schema and our own additional schemata.

**Comment by ArneBachmann** [comment]
That's great to hear and will help several dependent projects to continue independent tool development, I believe!

**Comment by codingpoets** [comment]
Great! Thank you for testing. I agree that we should rather have separate namespaces for the toolspecifics and not include them in the official schema. Especially since toolspecific nodes change with tool versions and should not be dictated in CPACS.

**Comment by MarAlder** [comment]
I looked again into this topic. The following example validates fine and looks promising to me:

First we exclude to baseTypes (because they are as well used by the toolspecific schema) and assign a namespace for cpacs_schema.xsd:
```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" 
            xmlns:html="http://www.w3.org/1999/xhtml" 
            xmlns:sd="http://schemas.xsddoc.codeplex.com/schemaDoc/2009/3" 
            xmlns:xlink="http://www.w3.org/1999/xlink"
            targetNamespace="http://www.cpacs.de"
            xmlns="http://www.cpacs.de"
            elementFormDefault="qualified">
            
    <xsd:include schemaLocation="cpacs_baseTypes.xsd"/>
        
    <xsd:element name="cpacs" type="cpacsType"/>

    <xsd:complexType name="cpacsType">
    ...

    <xsd:complexType name="toolspecificType">
        <xsd:annotation>
            <xsd:appinfo>
                <sd:schemaDoc>
                    <ddue:summary>
                        <ddue:para>toolspecificType</ddue:para>
                    </ddue:summary>
                    <ddue:remarks>
                        <ddue:para>Toolspecific type, containing specific data for the
                            analysis tools. <ddue:legacyBold>All types defined under this node will be removed from the schema with the next release. Toolspecifics can still be used but should be defined in their own namespaces.</ddue:legacyBold> This way an update of toolspecific types is no longer depending on CPACS releases.</ddue:para>
                    </ddue:remarks>
                </sd:schemaDoc>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="complexBaseType">
                <xsd:sequence>
                    <xsd:any minOccurs="1"></xsd:any>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
   ...
````

and the toolspecific schema, e.g., ts_liftingLine_2_5.xsd
```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" 
            xmlns:html="http://www.w3.org/1999/xhtml" 
            xmlns:sd="http://schemas.xsddoc.codeplex.com/schemaDoc/2009/3" 
            xmlns:xlink="http://www.w3.org/1999/xlink"
            targetNamespace="http://www.cpacs.de/liftingLine2.5"
            xmlns="http://www.cpacs.de/liftingLine2.5"
            elementFormDefault="qualified">
 
    <xsd:include schemaLocation="cpacs_baseTypes.xsd"/>
   
    <xsd:element name="liftingLine" type="liftingLineToolType"/>
    
        <xsd:complexType name="liftingLineToolType">
    ....
```

You may then "import" the corresponding files in the header:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cpacs xmlns="http://www.cpacs.de"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xmlns:ext="http://www.cpacs.de/liftingLine2.5"
       xsi:schemaLocation="http://www.cpacs.de cpacs_schema.xsd 
                           http://www.cpacs.de/liftingLine2.5 ts_liftingLine_2_5.xsd">
  <header>
    <name>name</name>
    <creator>creator</creator>
    <timestamp>2001-12-31T12:00:00</timestamp>
    <version>version</version>
    <cpacsVersion>cpacsVersion</cpacsVersion>
  </header>
  <vehicles>
      <aircraft>
          <model uID="aircraftUID1">
              <name>name</name>
          </model>
      </aircraft>
  </vehicles>
  <toolspecific>
      <ext:liftingLine>
          <ext:tool>
              <ext:name>name</ext:name>
              <ext:version>version</ext:version>
          </ext:tool>
          <ext:aircraftModelUID>aircraftModelUID</ext:aircraftModelUID>
          <ext:loadCases>
              <ext:loadCaseUID>loadCaseUID</ext:loadCaseUID>
          </ext:loadCases>
          <ext:toolParameters>
              <ext:usePOLINT>true</ext:usePOLINT>
              <ext:archiveMode>0</ext:archiveMode>
              <ext:parallelComputation>0</ext:parallelComputation>
              <ext:wingPanelings>
                  <ext:wingPaneling>
                      <ext:spanwise>0.0</ext:spanwise>
                      <ext:chordwise>0.0</ext:chordwise>
                  </ext:wingPaneling>
              </ext:wingPanelings>
          </ext:toolParameters>
        </ext:liftingLine>
    </toolspecific>
</cpacs>
```

**Comment by MarAlder** [comment]
The idea has been discussed to treat the toolType as a basic type in cpacs_baseTypes.xsd from which the toolspecific schema must inherit. This baseType must use ```xsd:enumeration``` for the version number to include a corresponding check of the tool version during schema validation.

I have experimented with the above example and learned that:
- Extending enumerated lists is not directly possible in xml ([Kiel 2008](https://www.ibm.com/developerworks/library/x-extenum/index.html)). One common workaround is to use ```xsd:union```. A valid  cpacs_baseTypes.xsd could be:
```xml
    <xsd:complexType name="toolType">
        <xsd:annotation>
            <xsd:appinfo>
                <sd:schemaDoc>
                    <ddue:summary>
                        <ddue:para>Tool identification</ddue:para>
                    </ddue:summary>
                    <ddue:remarks>
                        <ddue:para>Tool identification, containing name and version of a
                            tool</ddue:para>
                    </ddue:remarks>
                </sd:schemaDoc>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="complexBaseType">
                <xsd:sequence>
                    <xsd:element name="name" type="stringBaseType">
                        <xsd:annotation>
                            <xsd:documentation>Name of the tool</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="version">
                        <xsd:simpleType>
                            <xsd:union memberTypes="versionType extVersionType"/>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
   
    <xsd:simpleType name="versionType">
        <xsd:restriction base="xsd:string" />
    </xsd:simpleType>
   
    <xsd:simpleType name="extVersionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="2.5" />
        </xsd:restriction>
    </xsd:simpleType>
``` 
However, it looks to me that it is not possible to place the extended type (```extVersionType```) in the toolspecific namespace. 
[example_toolspecifics_union.zip](https://github.com/DLR-SL/CPACS/files/3325101/example_toolspecifics_union.zip)


- It would be possible to have a basicToolType in cpacs_baseTypes.xsd which provides the ```name```and ```version``` elements without using ```xsd:restriction```. One could inherit from this and add the remaining tool-specific information. However, the xml file does not properly validate:
[example_toolspecifics_baseType.zip](https://github.com/DLR-SL/CPACS/files/3325029/example_toolspecifics_baseType.zip)


I therefore propose to provide a template as shown below and agree that official toolspecific schemes must be based on this tamplate.
```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" 
            xmlns:html="http://www.w3.org/1999/xhtml" 
            xmlns:sd="http://schemas.xsddoc.codeplex.com/schemaDoc/2009/3" 
            xmlns:xlink="http://www.w3.org/1999/xlink"
            targetNamespace="http://www.cpacs.de/liftingLine2.5"
            xmlns="http://www.cpacs.de/liftingLine2.5"
            elementFormDefault="qualified">
 
    <!-- Include cpacs-specific types from cpacs_baseTypes.xsd --> 
    <xsd:include schemaLocation="cpacs_baseTypes.xsd"/>
   
    <!-- Global element -->
    <xsd:element name="liftingLine" type="liftingLineType"/>
    
    <!-- Basic tool-specific types -->
    <xsd:complexType name="toolBaseType">
        <xsd:complexContent>
            <xsd:extension base="complexBaseType">
                <xsd:sequence>
                    <xsd:element name="tool" type="toolType">
                            <xsd:annotation>
                                <xsd:documentation>Tool identification</xsd:documentation>
                            </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="toolType">
        <xsd:annotation>
            <xsd:appinfo>
                <sd:schemaDoc>
                    <ddue:summary>
                        <ddue:para>Tool identification</ddue:para>
                    </ddue:summary>
                    <ddue:remarks>
                        <ddue:para>Tool identification, containing name and version of a
                            tool</ddue:para>
                    </ddue:remarks>
                </sd:schemaDoc>
            </xsd:appinfo>
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="complexBaseType">
                <xsd:sequence>
                    <xsd:element name="name" type="stringBaseType">
                        <xsd:annotation>
                            <xsd:documentation>Name of the tool</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                    <xsd:element name="version" type="versionType"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:simpleType name="versionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="2.5" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- Type of the global tool element; must be an extension of toolBaseType -->
    <xsd:complexType name="liftingLineType">
        <xsd:annotation>
            ...
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="toolBaseType">
                <xsd:sequence>
                    ...
                </xsd:sequence>     
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType> 
```

The complete set of files for the example above:
[example_toolspecifics.zip](https://github.com/DLR-SL/CPACS/files/3324985/example_toolspecifics.zip)

**Comment by MarAlder** [comment]
I analyzed this issue in more detail (please read and comment the report) and made a small example. Please comment on this approach.

- [report](https://github.com/DLR-SL/CPACS/files/3667369/report_TS.pdf)
- [example files](https://github.com/DLR-SL/CPACS/files/3667360/example.zip)

**Comment by ArneBachmannDLR** [comment]
Amazing work! Thanks for the great report.
- ` my result` must be `may result`
- the relationship labels "used by" in Figure 3.3 are not clear - a tool doesn't use a schema. It accepts and creates XML files that can be validated by the schema
- is ["semantic versioning"](https://semver.org/) mentioned somewhere? what is the lower/upper boundary for supported cpacs versions of a tool?
- in case of using the `baseTypes.xsd`, does every toolspecific schema need to exist for each compatible CPACS version separately, i.e. `toolA_cpacs3_0` vs `toolA_cpacs_3_1`?
- provide a code snippet (Python) for the `<xsd:import>` validation approach given at the end of section 3

**Comment by MarAlder** [comment]
Thanks @ArneBachmannDLR for your comments! 
- [Report Version 1.1](https://github.com/DLR-SL/CPACS/files/3701602/report_TS.pdf)

---

- `my result` must be `may result`

changed

- the relationship labels "used by" in Figure 3.3 are not clear - a tool doesn't use a schema. It accepts and creates XML files that can be validated by the schema

added explanation in the figure description

- is ["semantic versioning"](https://semver.org/) mentioned somewhere? what is the lower/upper boundary for supported cpacs versions of a tool?

I added a comment. Schema versioning of the tools will be part of the tool vendor. Because the attribute is only for data traceability no lower/upper boundary should be supported but only the information, which tool version actually added the data.

- in case of using the `baseTypes.xsd`, does every toolspecific schema need to exist for each compatible CPACS version separately, i.e. `toolA_cpacs3_0` vs `toolA_cpacs_3_1`?

Bad formulation from my side. There will be no external `baseTypes.xsd`. In this context I added a remark and removed the sentence that the cpacs-schema could be imported into the tool-specific schema. I hadn't thought that sentence through enough before.

- provide a code snippet (Python) for the `<xsd:import>` validation approach given at the end of section 3

Added.

**Comment by sdeinert** [comment]
Would it be possible to already have the tool element itself being part of the namespace? This way all child elements would be inside this namespace without having to use the namespace prefix for each of them. This is one example how we use the namespaces to validate different tool specific data sets:

```
<toolspecific>
  <avl xmlns="http://www.cpacs.de/avl">
    <tool>
      <name>Athena Vortex Lattice</name>
      <version>3.35</version>
    </tool>
    <aircraftModelUID>model</aircraftModelUID>
    <toolParameters>
      <machNumber>0</machNumber>
      ...
    </toolParameters>
  </avl>
```
This would also prevent having to list the namespaces of all included toolspecifics in the header of the main CPACS file.

**Comment by MarAlder** [comment]
Yes, I just tried it. This way you don't need the prefix. 

Like this example with a given `schemaLocation`, right?:
```xml
<toolspecific>
    <tool>
        <name>Lifting Line</name>
        <toolVersion>1.5</toolVersion>
        <schemaVersion>1.1</schemaVersion>
        <liftingLine xmlns="http://www.cpacs.de/liftingLine" 
                     xsi:schemaLocation="http://www.cpacs.de/liftingLine ts_liftingLine.xsd">
          <tool>
              <name>name</name>
              <version>1.5</version>
          </tool>
          <aircraftModelUID>aircraftModelUID</aircraftModelUID>
          <loadCases>
              <loadCaseUID>loadCaseUID</loadCaseUID>
          </loadCases>
          <toolParameters>
              <usePOLINT>true</usePOLINT>
              <archiveMode>0</archiveMode>
              <parallelComputation>0</parallelComputation>
              <wingPanelings>
                  <wingPaneling>
                      <spanwise>0.0</spanwise>
                      <chordwise>0.0</chordwise>
                  </wingPaneling>
              </wingPanelings>
          </toolParameters>
        </liftingLine>
    </tool>
    </toolspecific>
```

**Comment by sdeinert** [comment]
Yes this looks good. However, I think the schema location is not strictly necessary as schemas can be assigned to specific namespaces. Yet, I am not sure if for example Tixi would see it the same way or if it would require the schema location entry to find the proper schema.

**Comment by MarAlder** [comment]
The schema location must just be linked with the namespace, so the `xsi:schemaLocation=...` can also be given in the header and the example would exactly follow your approach given above . 

I honestly just tested with the Eclipse validation method. Tixi needs one XML and one XSD file as input for validation. So I'm not sure how we deal with TiXI. But I want to make sure that we follow official XML recommendations, then we can figure out a way to implement the validation in TiXI.

**Comment by MarAlder** [comment]
I'll implement it like this (screenshot from documentation):

![bild](https://user-images.githubusercontent.com/43143741/69810604-94863980-11ec-11ea-9d1a-83a6ecb132ce.png)

The branch includes a toolspecific_template.xsd and an example XML file (5723e68).

**Comment by MarAlder** [comment]
**Update**: Introducing a namespace for CPACS conflicts with XPATH ([plasmasturm.org](http://plasmasturm.org/log/259/)). It would require major changes in TiXI/TiGL because a prefix must be assigned to properly query information from CPACS. 

Therefore, I removed the namespace (9893598) and the example shown above would change to:

```XML
<cpacs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../schema/cpacs_schema.xsd"
       xsi:schemaLocation="http://www.cpacs.de/myTool pathToToolspecificSchemaFile/toolspecific_myTool.xsd">
```

```XML
<toolspecific>
    <tool toolVersion="1.2.3" schemaVersion="1.0">
        <name>myTool</name>
        <myTool xmlns="http://www.cpacs.de/myTool">
            <parentElement>
                <childElement1>stringValue</childElement1>
                <childElement2>1.0</childElement2>
            </parentElement>
        </myTool>
    </tool>
</toolspecific>
```
