### ISSUE TITLE
Bug: Attached cpacs example is not valid

### ISSUE THREAD

**Issue by rainman110** [DLR-SL/CPACS#486]
The file https://github.com/DLR-LY/CPACS/blob/master/schema/cpacs_schema.xml contains many schema issues. This should be fixed!

**Comment by codingpoets** [comment]
Reopened this issue because the schema still shows validation errors. The eclipse plugin through which the example is created from a schema does not return a valid example.

**Comment by MarAlder** [comment]
I can confirm that the eclipse output is not valid. I furthermure tried with IntelliJ and Liquid Studio, but both examples are by far not complete...

I wonder whether anyone is even using the example or whether we can do without it and put some useful example files in the ```examples``` folder?

**Comment by MarAlder** [comment]
Example removed - problem solved...

Visual studio also failes to deduct a proper example xml-file. Eclipse just mentions in its documentation that the generated file might have _few errors_  ([link](https://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.wst.xmleditor.doc.user%2Ftopics%2Ftcretxml.html))... :).

I decided not to have an examle in the ```schema``` folder. Instead we should offer more examples to publish in the ```examples``` directory.
