### ISSUE TITLE
Restrict numeric values in schema via xsd:restriction

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-SL/CPACS#488]
E.g. for eta, xsi or #485 -1.0...+1.0

**Comment by MarAlder** [comment]
Implemented and used where possible (e.g., [posExcl0DoubleBaseType](https://www.cpacs.de/documentation/CPACS_3_4_0_Docs/html/c436d0a2-4e53-0819-97fd-e0922ea311a2.htm), [posExcl0IntBaseType](https://www.cpacs.de/documentation/CPACS_3_4_0_Docs/html/38008897-2afe-47f4-1446-6b38f3c35c39.htm), [axleAssemblyType](https://www.cpacs.de/documentation/CPACS_3_4_0_Docs/html/735c696a-fea6-ee57-2b55-672fffa0d069.htm) and others).
