### ISSUE TITLE
Flexible points in aeroPerformanceMap

### ISSUE THREAD

**Issue by codingpoets** [DLR-SL/CPACS#505]
In the AGILE project the need for a more flexible definition of the points in the aeroPerformanceMap was raised. In order to properly cover details in the main main points of the flight envelope such as low speed at low altitude and high speed at high altitude the definition of the points in the aeropPerformanceMap should be revised.
The following picture (mach on x-axis; altitude on y-axis) shows an example for a performance map which still contains some structure but refined the map at selected regions.
![grafik](https://user-images.githubusercontent.com/10432668/27479276-952026c0-5813-11e7-8d68-2b7df72c9270.png)

**Comment by MarAlder** [comment]
ToDo:
- [x] Quantitative analysis and comparison of four different schema proposals based on MULDICON dataset
- [ ] presentation and discussion of results with tool maintainers 
- [ ] 4 week publication of results/schema on GitHub 
- [ ] announcement via mail newsletter
- [ ] merge to CPACS 3.1 release

**Comment by MarAlder** [comment]
This is the latest proposal for the new aeroPerformanceMap definition for CPACS 3.1:

- [Report](https://www.cpacs.de/reports/report_APM.pdf)
- Example xml-file: [example_apm.zip](https://github.com/DLR-SL/CPACS/files/3300523/example_apm.zip)

**Comment by MarAlder** [comment]
Latest version:

- [schema illustration](https://cpacs.de/svgs/aPM2.svg)
- [commit](https://github.com/DLR-SL/CPACS/commit/d6a2c181a021aaeb0bb707565aed0445e9028108)

**Comment by MarAlder** [comment]
merged into develop (#589)
