### ISSUE TITLE
Documentation: transformation consistency 

### ISSUE THREAD

**Issue by MaloDrougard** [DLR-SL/CPACS#538]
In the chm documentation for wingElementType, we have:

> Mathematically spoken a element is a coordinate system that is translated, rotated and scaled relative to the section coordinate system.

But, as far I understand, and as explained in the image of the documentation bellow, the airfoil profile is described in the global coordinates system, then it is transformed by the wingElementType, then it is transformed by the wingSectionType.

This two definitions does not seems equivalent to me, in particular for rotation.

![wing-transformation-order](https://user-images.githubusercontent.com/5487810/38036604-5e442c7c-32a7-11e8-8b5f-e89e4cc8f2ad.png)

Best Regards,
Malo

**Comment by codingpoets** [comment]
Hi Malo,

I am not sure I share your doubts. The values given in the element transformations are relative transformations with respect to the section coordinate system. If you take the section coordinate system as a reference and then take the transformations described by the element you will end up with the element coordinate system. 

Best regards,
Jonas
