### ISSUE TITLE
seatElement Documentation Error

### ISSUE THREAD

**Issue by marcengelmann** [DLR-SL/CPACS#539]
Hi there, I am currently implementing the CPACS file format in the [PAXelerate Boarding Simulation](http://bauhausluftfahrt.github.io/PAXelerate/) and I discovered a mistake in the documentation. In the seatElement it is written that the x and y coordinates are relative to the cabin, whereas in the floorElement it is written that the points used are the forward center x coordinate and the center y coordinate. 

Having used an existing CPACS file now I can say that it is the case with every element (Seat/floor) that the y coordinate is based on the center of the object.

**Comment by codingpoets** [comment]
Hi,
Can I ask you how many CPACS files you checked and who created them?
If the current practice differs from the documentation we need to discuss whether we should change it. But for now I don't consider it an error.
