### ISSUE TITLE
Outdated documentation in CPACS3 release

### ISSUE THREAD

**Issue by bernhardmgruber** [DLR-SL/CPACS#563]
I just downloaded the CPACS3 release and found a mismatch between the documentation and the schema file regarding the definition of explicit stringers. After regenerating the documentation, they match up. I therefore guess, the generated documentation bundled with the release is not up to date.

Could you please update the documentation and bundle it again? Thank you!

**Comment by MarAlder** [comment]
I don't find a difference within the explicitStringersElement. Is it already resolved?

**Comment by MarAlder** [comment]
Sorry, I could not reconstruct the issue. Please contact me if the problem still exists.
