### ISSUE TITLE
Generic walls in the fuselage

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#571]
Based on a proposal from @sdeinert a new element "walls" has been added to the fuselageStructureType:

- [schema visualization](http://cpacs.de/svgs/wallsType.svg)
- [link to the schema branch](https://github.com/MarAlder/CPACS/tree/genericWalls/schema)

**Comment by MarAlder** [comment]
_Reinforcements_ have been moved to _../vehicles/structuralElements/structuralWallElements_.

It would make sense to inherit _lateralCapType_ from _capType_ in order to add the _placement_ element. However, this seems not to be valid in xsd, since capType is not a _sequence_ but an _all_-element [(...as I learnded from this discussion)](https://stackoverflow.com/questions/3808156/xsd-how-to-extend-a-type-with-an-unordered-list-of-elements). Thus, temporarily I just copied _area_ and _meterial_ to the new _lateralCapType_ to proceed working on the generic walls. A better solution avoiding the double elements is preferred, though.

**Comment by sdeinert** [comment]
Well then we can simply change the all to a sequence. I've been thinking about using inheritance on this node as well.

**Comment by MarAlder** [comment]
Because the idea comes from your proposal :smirk:. This would certainly be the easiest way. I'll check if this would affect other users who are already using the capType.

**Comment by MarAlder** [comment]
merged into develop
