### ISSUE TITLE
Fuselage compartment proposal

### ISSUE THREAD

**Issue by rmaierl** [DLR-SL/CPACS#572]
Currently, it is not possible to define an enclosed geometric volume within the fuselage.
The here proposed compartment element should overcome this shortfall.

An xsd schema with the proposed structure is attached to this issue and is open for discussion.

[Compartment.xsd.zip](https://github.com/DLR-LY/CPACS/files/2807267/Compartment.xsd.zip)

**Comment by MarAlder** [comment]
Implemented in [i572_i573_fuselage_compartment_tank](https://github.com/MarAlder/CPACS/commit/b43d7f878d9f44c50b0171cdc2b6267dea31ff2b)

- [schema graphics](https://cpacs.de/svgs/compartmentsType.svg)

**Comment by MarAlder** [comment]
closed by #584
