### ISSUE TITLE
Fuselage fuel tank issue

### ISSUE THREAD

**Issue by rmaierl** [DLR-SL/CPACS#573]
In the existing fuselageFuelTank is no possibility to define a parametric geometry.
The actual fuselageFuelTank should be replaced by the type proposed here.
The geometry definition of the new type refers to the proposed compartment elements definition -> #572 

The fuelTankVolumeType in the proposal has the same definition as the wingFuelTankVolumeType.
The wingFuelTankVolumeType should be replaced by the fuelTankVolumeType, that only one general type is defined.

The attached proposal is open for discussion.
[fuselageFuelTank.xsd.zip](https://github.com/DLR-LY/CPACS/files/2807297/fuselageFuelTank.xsd.zip)

**Comment by MarAlder** [comment]
Implemented in [i572_i573_fuselage_compartment_tank](https://github.com/DLR-LY/CPACS/compare/develop...MarAlder:i572_i573_fuselage_compartment_tank).

- [schema graphics](https://cpacs.de/svgs/fuselageFuelTankType.svg)

**Comment by MarAlder** [comment]
closed by #584
