### ISSUE TITLE
Missing uID in SparPositions 

### ISSUE THREAD

**Issue by rainman110** [DLR-SL/CPACS#577]
The spar segment uses spar position uIDs to define the geometry of the spar.

Unfortunately, the spar position types wingRibPointType and etaXsiPointType both dont have uids.

@rmaierl , @MarAlder , @RlanderRISCSW I would suggest the following change to cpacs. The choice of wingRibPointType and etaXsiPointType  is wrapped in a sparPositionType:
```xml
<sparPositions>
  <sparPosition uID="SP1">
    <sparPositionRib> <!-- [0, *]; new definition of wingRibPointType-->
      <ribDefinitionUID /> <!-- [1, 1] -->
      <ribNumber /> <!-- optional [0, 1], defaults to 1; ignored in case ribDefinitionUID points to an explicit rib definition -->
      <xsi /> <!-- [1, 1] -->
    </sparPositionRib>
  </sparPosition>
  <sparPosition uID="SP2">
    <sparPositionEtaXsi> <!-- [0, *]; etaXsiPointType -->
      <eta />
      <xsi />
      <referenceUID />
    </sparPositionEtaXsi>
  </sparPosition>
</sparPositions>
```

 This is more cpacs-like and also easier to implement in TiGL and probably also in other software.

For comparison, this is the current definition:
```xml
<sparPositions>
  <sparPositionRib> <!-- [0, *]; new definition of wingRibPointType-->
    <ribDefinitionUID /> <!-- [1, 1] -->
    <ribNumber /> <!-- optional [0, 1], defaults to 1; ignored in case ribDefinitionUID points to an explicit rib definition -->
    <xsi /> <!-- [1, 1] -->
  </sparPositionRib>
  <sparPositionEtaXsi> <!-- [0, *]; etaXsiPointType -->
    <eta />
    <xsi />
    <referenceUID />
  </sparPositionEtaXsi>
</sparPositions>
```

**Comment by rainman110** [comment]
@MarAlder Any decision fallen? I really like to start some TiGl implementation but need to know first, which definition I should implement.

**Comment by MarAlder** [comment]
No, not yet. I'm going to write to some users right now. Meanwhile the modified scheme looks like this:

sparPositionsType (contains 2..* the sparPositionType):
![sparpositionstype](https://user-images.githubusercontent.com/43143741/53400301-d6f4be80-39ad-11e9-9812-a7343ede1288.png)

sparPositionType:
![sparpositiontype](https://user-images.githubusercontent.com/43143741/53400304-d9571880-39ad-11e9-8fa3-6e121325e799.png)

It makes sense to set the multiplicity of the choice to 1..1, right?

[Here](https://github.com/MarAlder/CPACS/commit/4b8e6f49039a301ebfde9b6a8e6631ba97e216d0) are the changes to the "code".
