### ISSUE TITLE
The schema uses unknown tags

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-SL/CPACS#582]
I see `<xsd:superscript>` in the documentation parts of the schema. The `xsd:` namespace, however, doesn't define a `superscript` element. It's probably part of the documentation schema and needs a different prefix.

**Comment by MarAlder** [comment]
Thanks for your eagle-eye on syntax :) I've tried with MathML (```xmlns:mml="http://www.w3.org/1998/Math/MathML"``` namespace and ```<mml:math><mml:msup><mml:mi>X</mml:mi><mml:mn>2</mml:mn></mml:msup></mml:math>``` to do [this](https://developer.mozilla.org/de/docs/Web/MathML/Element/msup)), but Xsddoc does not recognize it. I have not found any solution which would work with XSDdoc. Thus, I replaced ```<xsd:superscript>``` with ```^``` and ```<xsd:subscript>``` with ```_``` in the documentation until we find a better solution (or an alternative way to document the schema).

[see changes](https://github.com/DLR-SL/CPACS/commit/3b2507a8ad69b8906dd0ad05925a95fb7fff13e7)
