### ISSUE TITLE
schema versioning

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#583]
In the course of introducing external toolspecifics (#484) the strategy of xml schema versioning must be rethought. Some best practice guides are introduced [here](http://www.xfront.com/Versioning.pdf). These should be analyzed with respect to our way of (future) working with CPACS.

**Comment by MarAlder** [comment]
I documented some thoughts about a proper versioning approach. I would like to make the `cpacsVersion` element optional in CPACS 3.2 and remove it in a future version as soon as we found a strategy to better trace data. 

The schema will get a version element in the schema header (not in the instance document) to provide an official place for the schema version number. 

The main goal is to avoid that complete data sets are only valid for a single schema version. 

Detailed explanations are given here:
- [Document](https://cpacs.de/reports/report_vs.pdf)

Looking forward for your opinions.

**Comment by joergbrech** [comment]
Option 1 might be dangerous, whenever there are semantic changes between CPACS versions. For example the interpretation (not the syntax) of guide curve profile points changed from CPACS 2 to CPACS 3, see #458. Without explicit version information a tool cannot know which interpretation to use.

**Comment by MarAlder** [comment]
True. But in general you agree with the reasoning that a data set should be valid with multiple schema versions? 

I think it's a weekness in our CPACS definition. We should try to make things as explicit as possible, maybe by adding a `schemaVersion` attribute to the baseTypes or something like that :thinking:. For the remaining implicit agreements a tool could interpret the data based on the cpacs schema it was designed for. If the tool writes back results into CPACS we might more traceability attributes (e.g. written by tool ... in version ...). But the problem remains if a tool will support multiple schema versions..

Good point. I will add it to the report to work out a solution.

**Comment by joergbrech** [comment]
Yes, I can definitely see how the current situation is too restrictive for many cases! But I also think we should keep an explicit safeguard for the cases, where a data set is valid for multiple schema versions, but does not necessarily comply with the associated CPACS definitions.

**Comment by MarAlder** [comment]
Maybe we could move option 2a of the [report](https://cpacs.de/reports/report_vs.pdf) down to the nodes were we might have semantic changes between CPACS versions. 

[Example](https://github.com/DLR-SL/CPACS/issues/605#issuecomment-549166485)

**Comment by MarAlder** [comment]
After a discussion with @CLiersch (he has contributed a valuable insight from daily practice) and @ArthurZamfir  we came to the conclusion that it is quite utopian to make the current CPACS explicit enough for the introduction of the above proposal (option 1). For our current way of working we need a global version element/attribute to enforce that a data set is valid according to the specified version. 

I would like to make this element/attribute optional, though. This way we can experiment with workflows being more flexible in terms of the version of datasets while assuring that we can continue our current approaches fixing the version for the whole document. 

With respect to TiGL this would mean that a dataset will either be rejected if no version element is specified (error message) or TiGL assumes the latest version (warning message). 

## Open questions
- Is it okay for everyone if we make the `cpacsVersion` element optional?
- Do we introduce the more official version 2b (`cpacsVersion` **attribute**) or do we continue with a `cpacsVersion` **element**? (basically referring to how complex the implementation in TiGL would be)

**Comment by MarAlder** [comment]
The current decision is to proceed with the `cpacsVersion` element and to set `minOccurs="0"`. Thus, any work can be continued as before and we can experiment with more flexible dependencies to the schema version.
