### ISSUE TITLE
Correct path in generateLibraries.bat and cleanNamespaces.bat

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#594]
In generateLibraries.bat the absolute path is given. This should be changed to be relative.

**Comment by MarAlder** [comment]
@ArneBachmann and @ArthurZamfir: any suggestions to prevent ```D:\...```? in the ```.bat```-files? Maybe work with variables at the beginning of the file to query the user's system configuration?

**Comment by ArneBachmann** [comment]
Where does the path come from? Who installs into this path? If it is a CI system, you could define the path in the build script or in a parametrized configuration variable.
To make the script portable, you could simply assume the called tools are on the path, and let the user do the path-keeping.

**Comment by MarAlder** [comment]
The CI ([appveyor.yml](https://github.com/DLR-SL/CPACS/blob/e45e23e499dc6a9ee5dd395f9a6c0c1aa9c14066/appveyor.yml#L1-L19)) is independent from the .bat files. So no need for current changes.
