### ISSUE TITLE
Introduce controlParameter to replace relativeDeflections

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#598]
The term ```relativeDeflections``` is misleading in CPACS because it is not directly connected to a physical deflection of a flap or similar control surfaces. Instead, it should be called ```controlParameter``` to account for abstract control commands used to realize novel control methodologies.

**Comment by MarAlder** [comment]
affected types:
- ```controlSurfaceDeflectionType ```
- ```controlSurfaceDeflectionVectorType```
- ```controlSurfaceHingeMomentMapType```
- ```gearDeflectionVectorType```
- ```landingGearSettingType```

**Comment by rainman110** [comment]
Even though I agree with you, that this renaming makes sense, I don't like this change, as it introduces an unecessary compatibility break with previous versions.
I am not sure, whether this change was discussed. If not, this change should have been communicated. This should not be an attack to you.

Here is some suggestion:
 1) try to avoid breaking changes, if not really required
 2) At the lease of a new CPACS version, name breaking changes explicitly, i.e. add a new header for breaking changes / incompatibilties with older version.
 3) Before introducing these changes, inform the major stakeholders (not everything has to be discussed!, but informing would be good)

**Comment by MarAlder** [comment]
Ok I'm very sorry, I should have informed you better! Back then I simply thought changes to control surfaces would not be to much of an issue because it was not yet implemented in TiGL and no one was yet using it in CPACS 3. And I was not yet to fully aware of this problematic due to my lack of experience with CPACS. 

However, to my little defence, it originated from changing the aeroPerformance Maps which was discussed at the developer meeting in Hamburg (but not finished at this point) and the corresponding changes were announced in an e-Mail to the whole CPACS community ("_RelativeDeflections renamed to control parameters_") providing more then 4 weeks to respond to these changes. I additionally provided a [list of changes](https://github.com/DLR-SL/CPACS/milestone/5?closed=1) 4 weeks earlier where this issue was on top and in the final relesase the changes were explicitly named in the header. So I considered my information policy not too bad - but obviously it can be improved.

But I learned from it during the past month doing CPACS and I will consider your points thoroughly in future.

**Comment by rainman110** [comment]
I want to stress again, that this was not a personal attack and I really think you are doing a good job.

I actually did not get your mail, but this probably my fault. I suspect that I am not in your mailing list. So you did your duty here.

What remains to be done in future is to really explicitly name breaking changes in the release log. In TiGL we have categories for API changes, new functions, TiGL Viewer, Bugfixes etc...
