### ISSUE TITLE
Set Jxy, Jxz and Jyz optional in massInertiaType?

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#621]
In conceptual and pre-design these values are often not known yet. Would it be ok to have it optional?

@DLR-BT, @sdeinert, @sfreund-DLR, @kngbuzzo

**Comment by sdeinert** [comment]
Yes, definitely! This information should be enriched along the process and is not available from the beginning.

**Comment by sfreund-DLR** [comment]
yes

**Comment by DLR-BT** [comment]
Yes!
