### ISSUE TITLE
Parametric Fuselage Profiles

### ISSUE THREAD

**Issue by sdeinert** [DLR-SL/CPACS#624]
Similar to the CST parametric definition of wing airfoils, it would be very useful to allow parametric fuselage profiles as an alternative to the existing point lists.
For this it would be possible to have a catalog of basic profile shapes to be supported at first, such as:
- Circle
- Ellipse (if circle with different scaling is not sufficient)
- Box/rectangle, with optional corner radius
- Super ellipse
- Two circles
- etc.

For one thing this would simplify creation of CPACS models; e.g. if you already know your fuselage shall have circular sections, you do not need to discretize a circle into a point list first. But also looking at the improved performance and robustness of CST wing airfoils in TiGL due to less complex spline geometries compared to point list airfoils, this seems like the logical step to also introduce something similar for fuselage profiles.
Additionally the parametrization of profiles would allow high fidelity optimization of fuselage shapes.

**Comment by CLiersch** [comment]
Thanks for bringing up this issue again. I think, it would be very useful to have a parametric definition for simple, typical fuselage shapes in CPACS. However, I would not place to many different types as a choice there. Thus, I would propose to introduce a generic super ellipse shape for fuselage profiles (consisting of separate definitions for upper side and lower side shape). In fact, this would cover most of the abovementioned cases, but is just one additional option to be handled.

**Comment by sdeinert** [comment]
I agree with you that the number of standard profiles should be kept small to avoid clutter. However, I would argue that, even though one can generate these shapes using a super ellipse, circle and square should be available separately so that they can be defined easily without having to provide a specific combination of parameters for the super ellipse.

My proposal would look like this in CPACS:
![profileGeometryType](https://user-images.githubusercontent.com/15669066/74742008-263a9b80-525e-11ea-9fa6-0bc5b45fb046.jpg)

With the standard profiles defined as:
![standardProfileType](https://user-images.githubusercontent.com/15669066/74742042-35b9e480-525e-11ea-88fb-c8bf51b2f106.jpg)

I don't know if radius is strictly necessary for the circle profile, as I would argue that these standard profiles should be normalized at least in width (best in both directions).

**Comment by rainman110** [comment]
I am also on favour to normalize all profiles to 1, so no radius would be required on case of the circle.

**Comment by rainman110** [comment]
There ratio with to hight should have the same name in the superellipse and in the rectangle.

Also, a circle is actually not required, since it is a special case of the super ellipse.

**Comment by sdeinert** [comment]
The reason for an extra circle definition is the simplicity. Yes, the super ellipse covers this but only for one specific set of parameters and, as the circle most likely would be the default profile for new components, I would like to circumvent the step of specifying 5 parameters just to get a circle with diameter 1.0.

heightRatio and widthToHeight have different meanings:

- **HeightRatio** affects how much height the lower half of the super ellipse covers and how much the upper half. The overall height and width stay at 1.0 regardless of its setting.
- **widthToHeight** changes the overall dimensions of the rectangle profile (either height or width, depending on what we agree on to be normalized).

**Comment by rainman110** [comment]
There is still the possibility to scale the profile afterwards using the CPACS transformation node. Therefore, widthToHeight is then not really required, right? Same argumentation as for the circle diameter/radius.

**Comment by MarAlder** [comment]
I guess `m_lower` and `n_lower` is what Wikipedia refers to as `a` and `b`?

- so called nil-able elements are possible as long as specified in XSD (see [here](https://www.data2type.de/xml-xslt-xslfo/xml-schema/referenzen-aus-schemas-in-xml/definition-von-nil-werten/))

- `square` (should be `rectangle`): to specify that the [exponent must be infinite](https://www.desmos.com/calculator/ylnqyluxah) to approximate a rectangle from a super ellipse is informal from a data modeling point of view and should be avoided in CPACS. Setting the exponents to [1 and rotating by 45deg](https://www.desmos.com/calculator/6ua1eikqnd) could technically be possible, but I admit that this is too cumbersome without a proper library function doing such transformations. So I propose to keep the `rectangle` element as choice.

- I know that my predecessors tried to avoid redundant definitions in CPACS if possible. I think that the data model must clearly show how the parameters are to be interpreted and, from a data modeling perspective, I am not necessarily against different approaches using choice elements. From the user's point of view, we must of course find a compromise between a not too complicated data generation (e.g. directly specifying a circle) and the effort to integrate CPACS in the tools (checking the different choice options in the tools). At this point, I suggest that we go without the `circle` for now and would ask the tool developers to check wheter the query for Exponent=2 is acceptabile in the implementation. If it causes too many problems, we can discuss adding the circle element. But that might be better than deleting an element afterwards.

**Comment by sdeinert** [comment]
No, I would say a and b should both be 1.0 so that width and height of the ellipse profile are always 1 and can be scaled differently afterwards.
`m_lower` and `n_lower` are the exponents (n in wikipedia). Using different values (n and m) for both items in the sum allows more flexibility in shapes.

**Comment by MarAlder** [comment]
> There is still the possibility to scale the profile afterwards using the CPACS transformation node. Therefore, widthToHeight is then not really required, right?

Could it be that we need the `widthToHeight` ratio for a clear definition of the `edgeRadius` in the `square/rectangle` element? Otherwise the rounded edges would be elliptical after transformation :thinking: But then again two superimposing ways of defining the ratio..

**Comment by MarAlder** [comment]
Ok, please have a look at this proposal and comment for further enhancements (compare with [online-documentation](https://www.cpacs.de/documentation/CPACS_fuselageProfiles/html/89b6a288-0944-bd56-a1ef-8d3c8e48ad95.htm)):
![grafik](https://user-images.githubusercontent.com/43143741/88820759-0969a300-d1c2-11ea-8d06-30bae28375d5.png)

#### [`square`](https://www.cpacs.de/documentation/CPACS_fuselageProfiles/html/0a3b2711-6c3a-2506-e6fd-3eae86280225.htm)
I don't really like empty elements in CPACS. Although the Eclipse validator successfully valdiates the empty element, it should be invalid according to this explanation: [xs:nillable](https://www.wilfried-grupe.de/nillable.html) (even with `elementFormDefault="qualified"`). Forcing the user to always add the `xs:nil` attribute also seems quite cumbersome to me. 

Thus, I made the [`cornerRadius`](https://www.cpacs.de/documentation/CPACS_fuselageProfiles/html/d17c77bb-2f0d-dd95-731e-583f40e1bde9.htm) obligatory ranging from (including) 0.0 to (excluding) 0.5.

#### [`superellipse`](https://www.cpacs.de/documentation/CPACS_fuselageProfiles/html/9c88da58-2c0e-5faf-03b7-5ec41ca0b1bf.htm)
My interpretation of the parameters is illustrated by [this plot](https://www.desmos.com/calculator/nhimssrerb) (pretty cool browser app, by the way..) and [these remarks](https://www.cpacs.de/documentation/CPACS_fuselageProfiles/html/9c88da58-2c0e-5faf-03b7-5ec41ca0b1bf.htm). Here, `R` is our `lowerHeightFraction`. Note that the exponents are [restricted to values above 0](https://www.cpacs.de/documentation/CPACS_fuselageProfiles/html/c436d0a2-4e53-0819-97fd-e0922ea311a2.htm) and `lowerHeightFraction` to [values between 0 and 1](https://www.cpacs.de/documentation/CPACS_fuselageProfiles/html/3d33af62-16c6-04b7-4bfb-c11ba6b49323.htm). With the first restriction, also `NaN` is somehow not a valid entry anymore. But as noted in the documentation the user may use `square` instead.

Please also find the corresponding [example file here](https://github.com/DLR-SL/CPACS/blob/parametricFuselageProfiles/examples/fuselageProfiles.xml).

 (@DLR-BT, @sfreund-DLR, @CLiersch, @jnwalther, @rainman110, @sdeinert, ...)

**Comment by MarAlder** [comment]
Since the rounded corners would no longer be circular when subsequently scaled from a square to a rectangle is performed afterwards within the fuselage definition, the square was replaced by a rectangle. Thus, I included a `heightToWidthRatio` and the `cornerRadius` (@sdeinert, I hope it's ok to not use `widthToHeightRatio` because I assumd a constant width when deriving the equation..)

![grafik](https://user-images.githubusercontent.com/43143741/95590525-73b28580-0a46-11eb-959e-3356fa56463b.png)

In principle the rounded edge could also be parameterized by a tangential ellipse. But maybe this is no longer relevant in practice. Below a screenshot of the current documentation. You can use the [desmos plotter](https://www.desmos.com/calculator/8ui2gxpvnm) to play with the parameters. 
![grafik](https://user-images.githubusercontent.com/43143741/95590838-d86de000-0a46-11eb-96d1-0514d5dba338.png)
