### ISSUE TITLE
Wing structure - Add rib posts

### ISSUE THREAD

**Issue by rmaierl** [DLR-SL/CPACS#628]
An additional element is required to improve the automated FEM model generation with our in-house tool Descartes.
The additional ribPost element represent the connection between a wing rib and a wing spar in an idealized way, modeled in a global finite element model.
The proposal is to add an optional element to the ribCrossSection node with the identical type as the rib caps.

The schema proposal is attached to this issue
![ribPosts_schema](https://user-images.githubusercontent.com/10923333/75697748-d15f4200-5cad-11ea-80ec-e5767c1dfafd.png)

**Comment by MarAlder** [comment]
I got good feedback from SL and BT colleages. So I'll implement a prototype and schedule it for CPACS 3.3.

**Comment by sfreund-DLR** [comment]
Hello,
I don't really understand which finite element should be modelled with the ribPost. Could you please explain this a little more and maybe also add an image?

**Comment by rmaierl** [comment]
The Rib posts will be modeled as rod elements.
Please find attached two screenshots of geometrical and structural representation of the rib posts.

![ribPosts_geom](https://user-images.githubusercontent.com/10923333/76296764-fc9dee80-62b6-11ea-8d7a-41b949fbffd2.png)
![ribPosts_fem](https://user-images.githubusercontent.com/10923333/76296787-07f11a00-62b7-11ea-9293-656f950f6f78.png)

Additionally, I added a FEM export in Nastran format with the rib posts. (please replace file ending)
ElemId: 41701433 - 41701438

[femMesh_out_bdf.txt](https://github.com/DLR-SL/CPACS/files/4311324/femMesh_out_bdf.txt)

**Comment by sfreund-DLR** [comment]
Thanks a lot! I got it. So the ribPost is located at the cross section between rib and spar. If this is the case, with the proposed definition, the ribPost at the front spar must be the same as at the rear spar, right?
Additionally, should the ribPost also be added to wingRibCellType?
@MarAlder : I just saw it on the above image:should ribReinforcement also be added to wingRibCellType?

best Regards

**Comment by MarAlder** [comment]
- XSD: [svg illustration](https://cpacs.de/svgs/ribPost.svg)

I implemented the proposal and added a [simple example](https://github.com/DLR-SL/CPACS/blob/7ae8ff11303806d2c9d969088ab5c097f8d7c735/examples/wingRib.xml#L132-L162) (77ff211). 

### Illustrating example
Let's see if I fully understand it. We are describing the vertical brackets/caps connecting the rib to the spars:
![ribSparIllustration](https://user-images.githubusercontent.com/43143741/76834175-f9fa4680-682c-11ea-87ea-b446b19b63ac.png)
[[Siedlak et al., 2017](https://link.springer.com/article/10.1007/s00163-017-0269-0)]

Once I define the ribPost elements it implicitly applies for all intersections to a spar, e.g. the front and rear edge of this simple rib element:
![example](https://user-images.githubusercontent.com/43143741/76834149-ef3fb180-682c-11ea-88e9-5cc22337bab3.png)

So we assume that they are always identical right?

### Further extensions
- How about extending/modifying the capType with respect to #558?
- What is your experience with `ribReinforcement`? 
    - Is it typical for ribs to also have stringers and frames?  
    - Is it semantically correct to describe stringers and frames in `ribCrossSection`?

**Comment by sdeinert** [comment]
As a first step I think it would be ok to assume the same cap for all crossings with spars.
If we would like to specify this in a more detailed way, we would somehow need to reference the spar (or possibly another rib) and provide an area/material combination for each of these spar references.
Regarding your questions for further extensions:
- #558 seems very detailed, so there it would be necessary to assure that simpler definitions for early stages are still possible. Something relevant in that regard would be cutouts in ribs and spars, as there always need to be holes in the structure elements for cables, pipes etc. If a new rib/spar cutout definition would be flexible enough, maybe some of the cases described in #558 could be solved through cutouts?
- Yes especially for larger rib or spar webs it becomes necessary to add reinforcements to avoid buckling of such large web patches. Concerning the nomenclature I don't really have an opinion.
