### ISSUE TITLE
Kinks in profiles

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#630]
@rainman110 has added a TiGL feature which accounts for kinks in profiles. The proposal #629 is merged to develop (see 3694d8f). Please have a look at the new `kinks` and `parameterMap` elements in the `curvePointListXYZType`:
- [Schema diagram](https://cpacs.de/svgs/kinks.svg)
-  [Documentation](https://www.cpacs.de/documentation/CPACS_ProfileKinks/html/d0271c9a-2b38-36af-5f3f-50d49dabdbda.htm)

![76216459-e9384800-6210-11ea-9d5d-40fb38a4574f](https://user-images.githubusercontent.com/43143741/76226438-27883400-621e-11ea-9c42-878a07b10450.jpg)

Let us know if you have any comments so that I can plan the implementation of the schema modification in the next CPACS release.

**Comment by ProgramAlarm1202** [comment]
Would it make sense to extend the definition of kinks in profiles #629 to guide cuves as well?
The `rXDirection` element could similarly be extended with `kinks `and `parameterMap `elements. The implementation in TiGL https://github.com/DLR-SC/tigl/issues/659 would be probably (hopefully) not that different.

**Comment by rainman110** [comment]
@ProgramAlarm1202 It is already possible to have a kink  in the guide curve AT a section. I would avoid defining additional kinks within a segment though.

**Comment by ProgramAlarm1202** [comment]
@rainman110 Good point. A limitation is that a section is always planar. But I suppose if you want a kink at a particular location, you can always insert an additional section.

**Comment by MarAlder** [comment]
More detailed information about the `parameterMap`: [TiGL Homepage](https://dlr-sc.github.io/tigl/towards-tigl-31.html)

**Comment by MarAlder** [comment]
@rainman110 @joergbrech : At the stakeholder meeting the question was raised whether we use 0 or 1 indexing for the `[kinks](https://www.cpacs.de/documentation/CPACS_development/html/d0271c9a-2b38-36af-5f3f-50d49dabdbda.htm)` vector (because XPATH starts with index 1 and I think many TiGL functions do so as well, right?). What do you think?

**Comment by MarAlder** [comment]
We have decided to use 1 indexing throughout CPACS (i.e., counting indices of vectors from 1). To distinguish the CPACS 3.3 schema from the TiGL 3.1 implementation (using 0 indexing) I renamed the corresponding parameters:

![grafik](https://user-images.githubusercontent.com/43143741/113163079-1ef70700-9240-11eb-8459-a9e5e00d3956.png)
