### ISSUE TITLE
Addition of configuration node to describe aircraft and payload configurations

### ISSUE THREAD

**Issue by ErwinMoerland** [DLR-SL/CPACS#636]
It is suggested to add a <configuration> node to the vehicle description in CPACS: /cpacs/vehicles/.../model/configurations/configuration, where the configuration settings are provided and linked to through uID's. Required for: weightAndBalance analysis, loadCase definitions, mission and point performance analysis

Within this node the following should be described:
- payload configuration 
- aircraft configuration, controlling the following elements:
  - high lift devices + controlDistributors
  - landing gear, brakes, airbrakes
  - mass case transitions

**Comment by MarAlder** [comment]
A first implementation (21547a0) includes the needs from the loadCase working group (#637):

![grafik](https://user-images.githubusercontent.com/43143741/85025690-feaa0000-b177-11ea-8c06-8ebf5c350150.png)

Control devices include all controllable elements, such as high lift devices, landing gear, brakes, airbrakes (and maybe afterburner as well).

In this context we also consided how we want to continue with the `aircraft/model/global` node. Maybe put the configuration node in there as well?
![grafik](https://user-images.githubusercontent.com/43143741/85026070-809a2900-b178-11ea-9c90-2d4f0f040bef.png)

**Comment by MarAlder** [comment]
Could be part of the `aircraft/global` node, right? :thinking:

**Comment by HHOPs** [comment]
I used the relational operator, as it was obligatory - would propose to set it optional, as a need can probably arise, when eventually introducing lapses for configuration changes (e.g. brake activation etc.)...

**Comment by MarAlder** [comment]
Ok, thanks for the clearification. I opened a [dedicated brach for this issue](https://github.com/DLR-SL/CPACS/tree/aircraftConfigurations) where I propose the following:

![grafik](https://user-images.githubusercontent.com/43143741/85520730-976ece80-b603-11ea-9380-518be721a079.png)

In a first step I would try to avoid relational parameters as it has to be discussed how to deal with it when used by, e.g., aerodynamic analysis.  

The mission definition (#634), load cases (#637) and maybe in future releases the aeroMaps (#505) could refer to this node by its `uID`.

**Comment by MarAlder** [comment]
Addition of control distributors as used in aeroMaps:

![grafik](https://user-images.githubusercontent.com/43143741/86114282-9db0ef00-baca-11ea-8ae6-7c4b02cb8e70.png)

**Comment by MarAlder** [comment]
A configurationType has been added with #660 which can be used for aeroMaps, aeroCases etc. Here an example of the aeroMap:
![grafik](https://user-images.githubusercontent.com/43143741/95425837-30bcb900-0945-11eb-9466-d27965178066.png)

It is furthermore implemented in the aeroCase element.

**Comment by MarAlder** [comment]
Since I was told that the `aircraft/model/global` node was originally intended for overall analysis results at the aircraft level, I set the `configurations` node back to `aircraft/model` (d989ece), as suggested at the very beginning. 

Perhaps the `systems` node would be a possible location for the `configurations` element as well. However, since this node may be subject to possible adjustments in the course of the system definition for CPACS 3.4, the current proposal is to leave it under `aircraft/model` for the time being.

**Comment by elPlaneador** [comment]
Good structure so far! 

![grafik](https://user-images.githubusercontent.com/47039730/97580407-8d1a7200-19f3-11eb-83bf-4d8a30a59252.png)

Would it make sence to insert an array of `segmentTypes`, along which flight `segmentType` each `configuration` can be flown? Needed for Trajectory Analysis for Noise Assessment. 

Would be great in CPACS V3.3

Could be look like: 
**Clean configuration:** 
`aircraft/model/configurations/configuration[1]/<segmentTypes>descent;cruise;climb;taxi</segmentTypes>`

**Full Flaps + Slats configuration**: 
`aircraft/model/configurations/configuration[2]/<segmentTypes>descent;approach</segmentTypes>`

**Intermediate Flaps + Slats [1] configuration:** 
`aircraft/model/configurations/configuration[3]/<segmentTypes>descent;takeOff;climb;acceleration</segmentTypes>`

**Intermediate Flaps + Slats [2] configuration:** 
`aircraft/model/configurations/configuration[4]/<segmentTypes>descent;takeOff;climb</segmentTypes>`

**Intermediate Flaps + Slats [3] configuration:** 
`aircraft/model/configurations/configuration[5]/<segmentTypes>descent;takeOff;landing</segmentTypes>`


The information, which flap setting has been intended for which `segmentType` is required to automize trajectory and procedure creation for the Noise Analysis. We need to know which flap and slat settings are intended to be used along approach and departure, even if any `configuration` could be used for both. Usually they are designated for specific flight phases.

**Comment by ErwinMoerland** [comment]
@elPlaneador thanks for the proposal! This kind of information linking should indeed be included.

Within linked Issue #634, [this comment in specific](https://github.com/DLR-SL/CPACS/issues/634#issuecomment-723079798), an initial suggestion for linking configuration settings to the mission segments is proposed. In this case, the ```cpacs/vehicles/../model/requirements/flightPerformanceCases/flightPerformanceCase``` node enables the requested assignment of configurations to specific segments of the referenced mission.

This mechanism allows the configurations node to stay mission-independent. 

The ```<flightPerformanceCases>``` node within the ```<requirements>```-definition on vehicle level intends to link all required information on mission/pointPerformance level:
- mission and point performance definitions,
- weightAndBalance cases,
- configuration settings,
- performanceMap settings.

The ```<requirements>``` node thereby forms the bridge between _vehicle-specific information_ (weightAndBalance, configurations, performanceMaps) and _flightPerformanceCases/controllabilityCases/trimCases_ (where the flightPerformanceCases include missions and pointPerformance definitions).

Is this a viable solution for the intended trajectory analyses?

**Comment by ErwinMoerland** [comment]
Forwarded todo from #635:

- [ ] check if the implementation of parameter lapses within the segments of the missionDefinition can hold 1:1 for providing configurational changes within the aircraft-specific <configurations> node

**Comment by MarAlder** [comment]
Will be closed for v3.3. Last comment from @ErwinMoerland will be referenced in a new issue for upcoming releases.
