### ISSUE TITLE
Addition of controllability requirements analyses

### ISSUE THREAD

**Issue by CarstenChristmann** [DLR-SL/CPACS#638]
The analyses of the controllability requirements have to be saved in CPACS for further processing, i.e. sizing of control surfaces/effectors. Based on required roll authorities (roll rate, roll acceleration onset/stop) and other requirements, the corresponding moments about the axes and their coefficients are determined. It is proposed to save these in

cpacs/vehicles/model/analyses/flightDynamics/controllabilityCases/controllabilityCase

Each controllabilityCase consists of

l_onset
m_onset
n_onset
cl_onset
cm_onset
cn_onset
l_stop
m_stop
n_stop
cl_stop
cm_stop
cn_stop

**Comment by MarAlder** [comment]
First version implemented in e5c3161

![grafik](https://user-images.githubusercontent.com/43143741/85135861-126c6980-b23f-11ea-8556-35254d677042.png)

Next steps
- [ ] add proper documentation
- [ ] check occurence
- [ ] example for unittests

**Comment by MarAlder** [comment]
Thanks for these [comments](https://github.com/DLR-SL/CPACS/commit/e5c316128413f235af4043a5060ae0eb38b44bba#commitcomment-40342423)

Addition to next steps:
- [ ] names should follow camelCase style
- [ ] rename alpha to angleOfAttack

What would be the benefit of a `fqCases` node? Will there be additional nodes under `flyingQualities` in future?

![grafik](https://user-images.githubusercontent.com/43143741/86442984-db05be80-bd0e-11ea-9409-6680a7c2bb73.png)

**Comment by MarAlder** [comment]
I implemented a proposal from @CarstenChristmann for renaming the `controllabilityCase` elements:

![grafik](https://user-images.githubusercontent.com/43143741/86444532-27ea9480-bd11-11ea-8a64-3e26cfefb08e.png)

**Comment by CarstenChristmann** [comment]
I have now produced the first data file with the proposed new structure. In order to distinguish easier between the cases I prefer to have the flight conditions included. That means, I suggest to add the following nodes on a optional basis:

.../controllabilityCases/controllabilityCase/machNumber
.../controllabilityCases/controllabilityCase/altitude
.../controllabilityCases/controllabilityCase/angleOfAttack

**Comment by MarAlder** [comment]
> 
> 
> I have now produced the first data file with the proposed new structure. In order to distinguish easier between the cases I prefer to have the flight conditions included. That means, I suggest to add the following nodes on a optional basis:
> 
> .../controllabilityCases/controllabilityCase/machNumber
> .../controllabilityCases/controllabilityCase/altitude
> .../controllabilityCases/controllabilityCase/angleOfAttack

The current status looks like this:
![grafik](https://user-images.githubusercontent.com/43143741/93588338-8be53680-f9ab-11ea-88f4-a7c35dce079a.png)

Or is it different from the state values in `controllabilityCase` because the values under `pointPerformance` are constraints?

**Comment by CarstenChristmann** [comment]
I am sorry, but there is a misunderstanding here. The path I have described is not unambiguous. It must read:

.../analyses/flightDynamics/controllabilityCases/controllabilityCase/machNumber
.../analyses/flightDynamics/controllabilityCases/controllabilityCase/altitude
.../analyses/flightDynamics/controllabilityCases/controllabilityCase/angleOfAttack

It is just to have flight conditions (from pointPerformanceDefinitions) and results at a glance.

**Comment by MarAlder** [comment]
Ok, but maybe just for my understanding: 
we have `.../analysis/flightDynamics/controllabilityCases/controllabilityCase/controllabilityCaseUID` referencing the data illustrated above https://github.com/DLR-SL/CPACS/issues/638#issuecomment-694793625. So if `machNumber` in `analysis` can differ from the constraint given in `pointPerformance`, then we could simply add the nodes. Otherwise require a little python/TiXI script or so to get the corresponding values at a glance. Only this way we would make sure that the data is always consistent.

**Comment by MarAlder** [comment]
Exclude `analysis/flightDynamics/controllabilityCases`, since @CarstenChristmann wants to first test a prototype in Diabolo project. No negative feedback so far on the remaining nodes. Will be presented and discussed on developer meeting before the official release.
