### ISSUE TITLE
Remove the term "master" from repository

### ISSUE THREAD

**Issue by ArneBachmannDLR** [DLR-SL/CPACS#639]
While many opinions exist on that topic, some find it sensible to remove all terminology referring to *master - slave* rhethoric. I found only one instance of `master node` in the CPACS schema, plus the obvious `master` branch, which is still widely used throughout the developer community, but could be renamed effortlessly as well (another branch can be made the default checkout branch).

**Comment by MarAlder** [comment]
It wouldn't hurt to rename the `master` branch to `main` or so. Feel free to modify the repository accordingly.

**Comment by ArneBachmannDLR** [comment]
I think the repo's maintainer has to rename the branch and update the default branch accordingly (if the default is master), and update relevant documention/tutorials. I don't seem to have those rights.

**Comment by MarAlder** [comment]
Might be true. Let's go through this after the next CPACS release, ok? I'm a little afraid of messing up the repo with all the open sub-branches :smirk:

**Comment by MarAlder** [comment]
Renamed `master` to `main`. Thanks @ArneBachmannDLR.
