### ISSUE TITLE
Landing gear conceptual design parameters

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#657]
A review of the proposed [landingGear definition](https://www.cpacs.de/documentation/CPACS_development/html/97ac15b1-410b-41a6-aeb3-00aa15314b6f.htm) (#632) revealed that in conceptual design the landing gear length must be specified without knowledge about the detailed geometric assembly. We need to find a solution to this avoiding redundancy of data.

**Comment by MarAlder** [comment]
Could this choice element solve the issue? A description of the definition of `totalLength` needs to be added. 

![grafik](https://user-images.githubusercontent.com/43143741/94560988-b19ff480-0263-11eb-9136-5df01ac0f2eb.png)

**Comment by sdeinert** [comment]
From my point of view, this would be a good solution. In case of the totalLength parameter, the transformation element can still be used to define the position and orientation of the landing gear leg so that the given length value can be placed in the 3D space.

**Comment by MarAlder** [comment]
I added a description and merged back to develop:

![grafik](https://user-images.githubusercontent.com/43143741/94894242-420b4e80-0489-11eb-83af-89da51a641f9.png)

**Comment by MarAlder** [comment]
Some additional thoughts on the spring deflection has led to a definition of static and compressed suspension travel:
![grafik](https://user-images.githubusercontent.com/43143741/94896981-070c1980-048f-11eb-9663-d9d40b14491e.png)
