### ISSUE TITLE
Conversion from CPACS2 to 3 may have issue

### ISSUE THREAD

**Issue by GodertdeZoetenGKNFokker** [DLR-SL/CPACS#677]
Hi DLR,

In some CPACS files that have been converted from CPACS2 to CPACS3 the spar definitions have not been converted correctlyn (using DLR tool cpacs2to3 (https://github.com/DLR-SC/cpacs2to3)). In some files the sparPosition still has the CPACS2 definition, so maybe the converter does not always work correctly?

Best regards,
Godert de Zoeten

**Comment by aidanjungo** [comment]
Maybe there error should be reported on the CPAC2to3 page: https://github.com/DLR-SC/cpacs2to3/issues

**Comment by MarAlder** [comment]
I hope that the [cpacs2to3 issue board](https://github.com/DLR-SC/cpacs2to3/issues) was helpful on this.
