### ISSUE TITLE
Wing axis system

### ISSUE THREAD

**Issue by GodertdeZoetenGKNFokker** [DLR-SL/CPACS#678]
In the <path> definition in CPACS2.3.1 and CPACS 3.0 (and maybe other versions) the documentation refers to the wing x-axis. (https://www.cpacs.de/documentation/CPACS_2_3_1_Docs/html/fda3a776-8768-8029-bd55-47efdbe97c80.htm)

I was wondering how exactly this axis is defined? I could not find it under the <wings> or <wing> nodes.
Thanks in advance!
Godert

**Comment by MarAlder** [comment]
Hi Godert,

the definition of the wing axes is defined [here](https://www.cpacs.de/documentation/CPACS_3_2_0_Docs/html/4a7e9500-c91b-42f3-8ce9-aadd38e86af4.htm). 

> Position of the wing: The position of the wing is defined using the transformation parameters. Using those parameters, the wing coordinate system is translated, rotated and scaled.

Does this help to answer your question?

**Comment by GodertdeZoetenGKNFokker** [comment]
Hi Marko,

Thank you, that is perfectly clear now!
