### ISSUE TITLE
stringerFramePosition definition at fuselage section

### ISSUE THREAD

**Issue by sdeinert** [DLR-SL/CPACS#680]
Modelling fuselage structures often makes it necessary to define a stringerFramePosition exactly in the plane of a fuselage section e.g. to meet the exact point of a change in the fuselage loft.

In the current definition this must be done via the positionX value by placing the position as close as possible to the x-position of the section. This, however, introduces precision issues that often fail in the geometry construction. Also in case a fuselage section is rotated and not parallel to the y-z-plane this is close to impossible.

Therefore, this issue proposes a small extension to the stringerFramePosition type introducing a choice for the positionX element to directly reference a fuselageSectionElement via its uID. This way the plane of the position is explicitly set to the plane of the section element. With this the intersection with the ray defined by referenceY and referenceZ can be performed and the referenceAngle applied inside this plane.

The addition of the choice element requires changing the *all* element into a *sequence*. Optionally this could be avoided by introducing another element level hiding choice inside.

![stringerFramePos](https://user-images.githubusercontent.com/15669066/100207649-201dcd80-2f08-11eb-9b88-6993b1e49191.jpg)

**Comment by MarAlder** [comment]
The proposal seems very useful to me. We will take it on the agenda of the next CPACS meeting and decide together how to proceed.  

@dlr-bt, @sfreund-DLR , @jnwalther, @rainman110, @joergbrech : what do you think about this idea?

**Comment by sfreund-DLR** [comment]
Hi, thanks for the proposal!
I understand the accuracy-reason for elements perpendicular to the global x-axis.

**If the element is not perpendicular** to the global x-axis, these questions arise:

1. What is the zero angle reference? Usually it is the global z-axis. Though, this does not work if the z-axis is perpendicular to the element plane.
2. How would you define coordinates in between the element planes, since positionX would not work in general.
3. Could you please add an description/image to the answer of 1. for the cpacs documentation. I think this is really important to others who start with cpacs fuselages.

**Comment by MarAlder** [comment]
@sdeinert @rmaierl, in the last stakeholder meeting you mentioned that you support the documentation with pictures. I took this from your slides:

![grafik](https://user-images.githubusercontent.com/43143741/111334558-f386f080-8673-11eb-9f79-b7a410f5999f.png)


- [ ] Would you and @sfreund-DLR check what else we need in terms of text and pictures to provivde comprehensive documentation?

**Comment by sdeinert** [comment]
Hi everyone,
Regarding the open questions by @sfreund-DLR  I would suggest the following:
1. 0 degrees is always "up" (positive z-direction) in the _fuselage_ coordinate system. Global system does not really makes sense for children of the fuselage in my opinion. If the element is tilted in some way, the projection of the fuselage z-axis onto the element plane would be the reference direction. Should someone build a fuselage ignoring all conventions by e.g. aligning the fuselage's length direction along the fuselage coordinate system z-axis through moving and rotating all sections accordingly, then this is asking for trouble and should not be supported.
2. Not sure if I understand this problem correctly. x-position is also measured in the fuselage coordinate system. With the convention of the fuselage being defined along its own coordinate system's x-axis this should not pose any problem. Not adhering to this convention causes issues as under 1.
3. Are the pictures added by @MarAlder sufficient? Otherwise we can check if anything better is availalbe.

Hope this helps, let me know if there are any other points that need clarification.

**Comment by sfreund-DLR** [comment]
Hi, 
my questions were related to the statement above 

> Also in case a fuselage section is rotated and not parallel to the y-z-plane this is close to impossible.

When defining a fuselage always along the x-axis (which I also strongly support) then everything is fine and the images are sufficient. When I wrote these questions, I thought you also wanted to add the option for heavily rotated segments. But it seems this is not the case. So everything is fine with the given image and the definition itself.

best regards

**Comment by MarAlder** [comment]
Super that the issue could be clarified.
