### ISSUE TITLE
Extend New AeroCase definition by strip (and chordwise part) border coordinates

### ISSUE THREAD

**Issue by CLiersch** [DLR-SL/CPACS#692]
During beta-testing of the new AeroCases for CPACS V3.3 it turned out that one important piece of data is still missing:

The coefficients of strips and chordwiseParts already have a &lt;reference&gt; node with a corresponding reference point to make them usable e.g. for structural sizing of a beam model. But for other kinds of usage (like when calculating and adding viscous drag for a given strip distribution), it becomes apparent that the border/corner coordinates  of the strips and chordwiseParts are not available in the dataset. Of course it is possible to reconstruct these borders based on the assumption that the strip moment reference point is in the strip center on 1/4 chord, but that is an implicit expectation and not guaranteed to be always correct.

Thus, the proposal is to add two (mandatory) segment-eta coordinate nodes as borders to each strip, a "from" border and a "to" border. They should be given in relative segment coordinates (eta), as the strip is s sub-structure of a certain segment. For the chordwiseParts, a corresponding (mandatory) "from" and "to" Xsi seems appropriate.

![image](https://user-images.githubusercontent.com/23696124/108504241-dac62d80-72b5-11eb-8ba6-a299c44fcdc6.png)

**Comment by MarAlder** [comment]
Fine for me.

**Comment by CLiersch** [comment]
After more discussions , two further aspects appeared:
1.) The from/to nomenclature creates a lot of redundancy, as a "to" border should always be identical to the subsequent "from" border (for strips, as well as for chordwise parts). So, the proposal is to use only "to"-borders explicitly. That means, for the first element, "from" would imlicitly be "0", while for the others it would be the "to" border from the previous element. 

2.) While the strip etas are always identical at the strip leading  edge and trailing edge (each strip side border goes along a segment iso-eta coordinate), the Xsi-coordinates of a chordwise part are not necessarily the same on the left and right side (Imagine an aileron on a tapered wing.: It might have the same absolute chord on left and right side - so, the leading edge would not be aligned with an iso-xsi-coordinate. When creating a strip/chordwisePart at that location, it would really be favorable to have a chordwise part that is really identical to the aileron borders). So, we need the oppotunity to specify separate Xsi-coordinates for bothe sides of the chordwise part separately. 

Bringing together these two further aspects leads to the following proposal:

                      <coefficientsBreakdown>
                        <wings>
                          <wing>
                            <wingUID>Wing</wingUID>
                            <coefficients/>
                            <segments>
                              <segment>
                                <segmentUID>Seg_1</segmentUID>
                                <coefficients/>
                                <strips>
                                  <strip>
                                    <toSegmentEta>0.0701677</toSegmentEta>
                                    <coefficients/>
                                    <reference>
                                      <area>1.3001</area>
                                      <length>1.82593</length>
                                      <geometryPoint>
                                        <x>20.975</x>
                                        <y>-16.5304</y>
                                        <z>0.972135</z>
                                      </geometryPoint>
                                    </reference>
                                    <chordwiseParts>
                                      <part>
                                        <innerBorderToSegmentXsi>0.0666667</innerBorderToSegmentXsi>
                                        <outerBorderToSegmentXsi>0.0666667</outerBorderToSegmentXsi>
                                        <coefficients/>
                                        <reference>
                                          <area>0.0866317</area>
                                          <length>0.121729</length>
                                          <geometryPoint>
                                            <x>20.5489</x>
                                            <y>-16.5304</y>
                                            <z>0.970097</z>
                                          </geometryPoint>
                                        </reference>
                                      </part>

**Comment by MarAlder** [comment]
Like so?:

## Strip documentation
![grafik](https://user-images.githubusercontent.com/43143741/111290774-c708af80-8646-11eb-9e82-607bea64658b.png)

## Part documentation
![grafik](https://user-images.githubusercontent.com/43143741/111290883-dee03380-8646-11eb-9c82-29a0598c9fe5.png)

## XSD graph
![grafik](https://user-images.githubusercontent.com/43143741/111288340-5d87a180-8644-11eb-97bb-1015e7c9cf87.png)

**Comment by MarAlder** [comment]
Finished for now, I would say.
