### ISSUE TITLE
Landing gears: Discussion on remaining issues

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#693]
There will be a working group to exchange on the following remaining issues w.r.t. the new landing gear definition #632:

- linking with controlDistributors
- naming of parent nodes
- extensibility, e.g. Oleo
- exotic landing gears

Conact cpacs[ät]dlr.de to get your login to the online meeting on **Tuesday, 09/03/2021 at 09:30-11:30**. Any contribution is very welcome.

**Comment by MarAlder** [comment]
Compare the following status updates with the modified [example file](https://github.com/DLR-SL/CPACS/blob/223059e4e2a8d7c22a518e76e5db252239ce8513/examples/landingGears.xml).

## Linking with controlDistributors
Please have close look at the current implementation. In the case of binary functions (braked/unbraked) I propose to use a simpler implementation omitting the `steps`:
![grafik](https://user-images.githubusercontent.com/43143741/110937106-31151200-8332-11eb-93a8-0f1d41e876d7.png)

## Naming parent nodes
In our last working group meeting we decided to implement the `landingGears/landingGear` approach.
![grafik](https://user-images.githubusercontent.com/43143741/110937405-9d901100-8332-11eb-8b48-982fd8946916.png)

## Extensibility, e.g. Oleo
In the working group meeting we concluded that a potential extension is possible in future.

## Exotic landing gears
We identified that knee landing gears can not be modeled in detail. However, due to missing use-cases we decided to stick to the current implementation.

**Comment by MarAlder** [comment]
## Naming of parent node for retraction, steering and braking

What do you think? `control`, `actuation`,`global`, something else? I think one of `control` or `actuation` describes it quite well and distinguishes it a little bit from the meaning of `global` in other places of CPACS.

![grafik](https://user-images.githubusercontent.com/43143741/111436210-00eabc00-8702-11eb-86c5-a545fb801996.png)
![grafik](https://user-images.githubusercontent.com/43143741/111436528-6048cc00-8702-11eb-9ec4-202fc101805c.png)

# Remaining open points:
- [ ] Feedback on linking with controlDistributors
- [ ] Naming of parent node for retraction, steering and braking

**Comment by HHOPs** [comment]
I would prefer to name the base node `**control**` - as the component functions below this node are not necessarily always based on actuation etc.

As for the linking of the respective LDG-control-functions with the controlDistributors - e.g.:
...
<commandInputs mapType="vector">0;1</commandInputs>
<controlElements>
    <controlElement>
        <controlDeviceUID>**extPathLG1**</controlDeviceUID>
        <controlParameters mapType="vector">0;1</controlParameters>
    </controlElement>
...
from the controlDistributor section links via UID with 
...
<extensionPath uID="**extPathLG1**">
...
This allows for a consistent uID search. When found it is clear, which action is linked with the respective parameters...

In general, this is a very good and well required method of linking parameters and actions/functions - therefore OK for me! Thanks Marko for the proposal and rapid way forward!

**Comment by MarAlder** [comment]
Thanks for all your contributions. I think we can work with this definition now.
