### ISSUE TITLE
Common nomenclature: air speed

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#695]
We should try to introduce a naming convention for velocities. 

Current implementations in the 3.3 beta-release are:
- CAS: 
    - [constraintSettingsType](https://www.cpacs.de/documentation/CPACS_development/html/cb494364-78de-2e7b-808a-86c5b68547ac.htm)
    - [missionSegmentEndConditionType](https://www.cpacs.de/documentation/CPACS_development/html/41b29de4-1ed4-60a3-c5b6-e23f52ea6ae5.htm)
    - [missionStartConditionType](https://www.cpacs.de/documentation/CPACS_development/html/65660f5e-099d-7e7f-e76d-04f7aeb03982.htm)
- vTAS: [flightDynamicsTrimResultType](https://www.cpacs.de/documentation/CPACS_development/html/f60a132f-d2e4-1a0a-78e2-fc26196d5382.htm)
- cAS: [flightPointType](https://www.cpacs.de/documentation/CPACS_development/html/a14a7a2c-43db-3217-3f66-4a75f602cc2e.htm)
- tAS: [flightPointType](https://www.cpacs.de/documentation/CPACS_development/html/a14a7a2c-43db-3217-3f66-4a75f602cc2e.htm)
- vCAS: [pointPerformanceConstraintsType](https://www.cpacs.de/documentation/CPACS_development/html/87742e8c-63fb-c95e-bc4b-b0db4bfa64bb.htm)
- trueAirSpeed: [flightEnvelopeSpeedType](https://www.cpacs.de/documentation/CPACS_development/html/02775a84-dc96-242c-527b-9de6d081b71c.htm)

## Decisions:
- Should we in future distinguish between calibrated and true air speed or rely on conversion with atmospheric model? 
- Which style to use: **calibratedAirSpeed**, **CAS**, **cAS** or **vCAS**?

**Comment by HHOPs** [comment]
- I think we should rely on the ISA-atmosphere for conversion CAS2TAS - as this is normed and commonly used (ISO 2533:1975, https://www.iso.org/standard/7472.html)
- For the symbol representation I would recommend to use the respective norms - ISO 1151-1:1988, https://www.iso.org/standard/5699.html

**Comment by MarAlder** [comment]
`For the symbol representation I would recommend to use the respective norms - ISO 1151-1:1988, https://www.iso.org/standard/5699.html`

I have no access to this. What does the norm say?

I also got the feedback that we are writing most parameters as full names, e.g. `machNumber`, `altitude`, `angleOfAttack`, etc, and therefore we should also try to write velocities as `calibratedAirSpeed` and `trueAirSpeed`.

**Comment by MarAlder** [comment]
Renamed to `calibratedAirSpeed` and `trueAirSpeed` for:
- **constraintSettingsType** (missionDefinition)
- **missionSegmentEndConditionType** (missionDefinition)
- **missionStartConditionType** (missionDefinition)
- **flightDynamicsTrimResultType** (flightDynamics analysis)
- **pointPerformanceConstraintsType** (pointPerformance)
- **flightEnvelopeSpeedType** (flightEnvelope)

:exclamation: :exclamation: :exclamation: **This breaks backwards compatibility, so please review carefully.** However, the upper types are used within current or planned changes in the 3.3-RC.

**Not** changed yet for (as no reply from stakeholder and currently strongly used in the `trajectory` node):
- **flightPointType**
