### ISSUE TITLE
performanceRequirements: linking performanceMaps

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#697]
Should the possiblility to link performance maps, as introduced in the current beta release candidate under [`flightPerformanceCase`](https://www.cpacs.de/documentation/CPACS_development/html/3e4d0e68-17b8-3016-a36a-97a86b2cd340.htm), also be added to `controllabilityCases` and `trimCases`?

![grafik](https://user-images.githubusercontent.com/43143741/110650977-4fa4cd00-81bb-11eb-815b-5796f0728ff3.png)

**Comment by ErwinMoerland** [comment]
yes this seems to make sense. 

Examples:
- there could be datasets having there are separate enginePerformanceMaps for different powertrain settings. I can imagine that certain controllabilityCases / trimCases should be studied for a given powertrain setting, so one has to be able to link the correct performanceMap to the cases.
- The same applies to aeroPerformanceMaps (e.g. controllabilityCases for configurations with and without external fuel tanks showing a significantly different aerodynamic behavior).

**Comment by MarAlder** [comment]
Ok, done:

![grafik](https://user-images.githubusercontent.com/43143741/112621423-00e96b00-8e2a-11eb-8078-cf442d9b774d.png)
