### ISSUE TITLE
Superposition of control surface deflections

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#710]
Thanks @cliersch for this procedure of adding control device deflections:

### Documentation of `controlDistributorType`
![grafik](https://user-images.githubusercontent.com/43143741/112983887-7cb32280-915e-11eb-8cce-051cd6084eaf.png)

### Documentation of `aeroMapType`
![grafik](https://user-images.githubusercontent.com/43143741/112984013-9fddd200-915e-11eb-9c60-21cbb90534a7.png)

**Comment by CLiersch** [comment]
I would propose to use an ordered list with a numbering, as the text is self-referencing specific list items by number.

**Comment by MarAlder** [comment]
Me too, but I couldn't find out how to do it with the `ddue` namespace: 
```XML
<ddue:list class="?">
```

**Comment by MarAlder** [comment]
List items using paragraphs that start with `1) ...` are looking very ugly. I'll just use a combination of bullet items and manual enumeration:

![grafik](https://user-images.githubusercontent.com/43143741/113158371-05ec5700-923c-11eb-9f96-fa10b9dbdc63.png)

**Comment by MarAlder** [comment]
Thanks for this contribution. I'll close this issue.
