### ISSUE TITLE
Harmonization of the nomenclature

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#711]
With regard to the CPACS 3.3 release, some larger adjustments and enhancements such as `aeroCases`, `loadCases` and `missionDefinitions` or `pointPerformances` were discussed. During and after the stakeholder meetings there were some requests to harmonize the nomenclature before the official finalization. This issue will summarize the major changes:

### Naming conventions:
I added the proposed development guidelines (#704) to [development.md](https://github.com/DLR-SL/CPACS/blob/nonmenclatureHarmonization/development/development.md#development-guidelines). The proposed [naming conventions](https://github.com/DLR-SL/CPACS/blob/nonmenclatureHarmonization/development/development.md#naming-conventions) are applied in a [common structure for analysis elements](https://github.com/DLR-SL/CPACS/blob/nonmenclatureHarmonization/development/development.md#example-analysis-node):

> The figure below shows an example of a typical analysis node. A complete analysis case is summarized with `case`. There is no need for a plural parent element `..Cases` if there exists no alternatives. In other words, if `myDiscipline` groups different analysis cases, a plural parent element should be applied (e.g., `flightDynamics`: `trimCases`, `controllabilityCases`, etc.). In addition to a `uID` attribute as well as the usual `name` (obligatory) and `description` (optinoal) elements, a `case` consists of two parts. 

> The first part should be labeld as `specification` and contains the input parameters for the corresponding analysis (since these may represent an output for other disciplines, the name `input` should be avoided at this point; also the term `definition` is a bit too imprecise). There are a few typical elements which should be reused for the specification if it makes sense. This includes an `environment` element of type `environmentType`, which provides an `atmosphericModel` and a corresponding `deltaTemperature`. A node named `configuration` of type `configurationType` provides a `uID` reference to predefined configurations as well as additional individual control devices that can be superposed to this configuration. This set of inputs might be further enriched by own parameters such as `uID` references to existing components or individual parameters based on the simple `baseTypes`. 

> The second part contains the actual analysis data and its name may depending on the discipline (`myResults` used as a placeholder). 

![grafik](https://raw.githubusercontent.com/DLR-SL/CPACS/nonmenclatureHarmonization/development/images/analysisTemplate.png)

The naming conventions and harmonization of analysis elements will affect the following implementations:

### aeroCases
before:
![grafik](https://user-images.githubusercontent.com/43143741/113144682-ce76ae00-922d-11eb-918c-eb55cf6d11f6.png)

after:
![grafik](https://user-images.githubusercontent.com/43143741/113144942-1f86a200-922e-11eb-9d18-357a825cb968.png)

### flight/groundLoadCases
before:
![grafik](https://user-images.githubusercontent.com/43143741/113147504-21059980-9231-11eb-80b1-e16880e7ed87.png)

after:
![grafik](https://user-images.githubusercontent.com/43143741/113145740-18ac5f00-922f-11eb-9f1c-11a3074fc136.png)

### aeroMaps (will not be part of CPACS 3.3!)
We also propose to harmonize the `aeroMaps` in a future release:

now:
![grafik](https://user-images.githubusercontent.com/43143741/113147297-ef8cce00-9230-11eb-91da-84375853320c.png)

future:
![grafik](https://user-images.githubusercontent.com/43143741/113147418-0c290600-9231-11eb-93b1-9b441aa609f8.png)

### Summary of analyses nodes
So I would say it looks really harmonic:
![grafik](https://user-images.githubusercontent.com/43143741/113147901-8e192f00-9231-11eb-99c8-49e8501e136e.png)

### missionDefinitions
before:
![grafik](https://user-images.githubusercontent.com/43143741/113146780-5fe71f80-9230-11eb-9c08-40855ed7b021.png)

after:
![grafik](https://user-images.githubusercontent.com/43143741/113146924-8907b000-9230-11eb-89ba-291d5fe921de.png)

### pointPerformances
before:
![grafik](https://user-images.githubusercontent.com/43143741/113147115-bbb1a880-9230-11eb-8852-e9f284e5ba60.png)

after:
![grafik](https://user-images.githubusercontent.com/43143741/113147203-d421c300-9230-11eb-9965-27f9115bda84.png)

**Comment by ErwinMoerland** [comment]
Hi @MarAlder, looks good and makes the structure much more clear! I am very happy with the  creation and application of the common nomenclature as well as with the more harmonized common structure of analysis node contents .

One thing to consider to further harmonize the `<analysis>` node contents:

_"The second part contains the actual analysis data and its name may depending on the discipline (myResults used as a placeholder)."_

for _myResults_ we now have:

`<aeroCase> `-> `<aeroData>`
`<flightLoadCase>, <groundLoadCase>, <crashLoadCase>` -> `<loads>`
`<aeroMap>` -> `<aeroPerformanceMap>, <aeroLimitsMap>`

should we provide a hint on naming conventions for the _myData_ node? We can distinguish two kinds of result nodes: _data_ and _maps_. Then we could have the following:

`<aeroCase> `-> `<aeroData>`
`<flightLoadCase>, <groundLoadCase>, <crashLoadCase>` -> **`<loadData>`**
`<aeroMap>` -> `<aeroPerformanceMap>, <aeroLimitsMap>`

i.e.: the xxxData and xxxMap represent the base nodes for the actual analysis data. This convention could be used throughout the complete `<analysis>` node

**Comment by MarAlder** [comment]
Good suggestion!

**Comment by MarAlder** [comment]
Implemented via e485289 (see [development.md](https://github.com/DLR-SL/CPACS/blob/develop/development/development.md))

![grafik](https://user-images.githubusercontent.com/43143741/114033850-eb3e6180-987d-11eb-81ed-1647f2cf3987.png)

**Comment by MarAlder** [comment]
No feedback; so I assume everything is harmonic now :)
