### ISSUE TITLE
Naming conventions: Requirements, Reqs, Definitions and Defs

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#714]
### Problem
Due to the length of the word `Requirements`, we have chosen the abbreviation `Reqs` when revising the `performanceRequirements` for CPACS 3.3. This may result in long XPath strings.  However, it was noted that this is inconsistent with other node names where we write out `Definitions` and do not abbreviate to `Defs`. 

![grafik](https://user-images.githubusercontent.com/43143741/116985241-7f101b80-accc-11eb-927e-5618d5cd5259.png)

### Proposals
1. We also abbreviate `Definitions` (resp. `Definition`) as `Defs` (resp. `Def`).
2. We keep the current state as `Requirements` is a bit longer than `Definitions` and then sometimes use abbreviations and sometimes not.
3. We consistently write out everything according to the motto: as expressive as possible. In the XML file the tags are listed underneath anyway and for the XPath strings linebreaks could be used.

I prefer solution 3. What do you all think?

**Comment by ErwinMoerland** [comment]
I prefer solution 3. The 'delta' in XPath length achieved due to using abbreviations does not seem too large (saving a couple of characters compared to an already relatively long xpath). I do prefer the 'as expressive as possible' motto here.

**Comment by CarstenChristmann** [comment]
Although I prefer shorter names I vote for the proposal which causes a minimum of necessary changes in the released schema V3.2. This will reduce the impact on already existing tools.

**Comment by MarAlder** [comment]
closed by #716
