### ISSUE TITLE
Typo in mPylon mass breakdown

### ISSUE THREAD

**Issue by marcengelmann** [DLR-SL/CPACS#720]
Hi,

I discovered that there is a typo in the following path:

'cpacs/vehicles/aircraft/model/analyses/massBreakdown/mOEM/mEM/mStructure/mPylons/mPylon**s**'

The lowest level should be mPylon and not mPylons I guess, as it contains a list of single pylon masses.

**Comment by MarAlder** [comment]
Ups, thanks!! Closed by 6130b1e.
