### ISSUE TITLE
Double definition of old deck elements

### ISSUE THREAD

**Issue by marcengelmann** [DLR-SL/CPACS#763]
Hi Marco,

I tried the CPACS 3.4 beta and i noticed that in the xsd there still are some double definitions:

- cabGeometryType and cabinGeometryType
- deckDoorType and cabinDoorType
- ...

It seems that the old definitions haven't been removed yet completely. 

Are you planning on removing them before the release? 

Marc

**Comment by MarAlder** [comment]
Hi Marc,

`cabGeometryType` and `cabinDoorsType` are not used by any element anymore. I'll delete it before releasing CPACS 3.4.

Thanks!
