### ISSUE TITLE
massBreakdown: definition of mLandingGear

### ISSUE THREAD

**Issue by 0bernd** [DLR-SL/CPACS#764]
Hello CPACS-Team, 
since the landingears elements are now more generic, it would make sense to proceed in a similar way for the mlandingGears elements, stop using mMainGear/mNoseGear.
Maybe also add masses of subcomponents such as mainstrut, actuator etc. according to the landingGear definition if it makes sense to use it otherways leave it. Can be helpful for landing gear mass analysis.

And more like a question: 
If a landingGear is retracted the landingGear CoG is different, how to work with this issue? Normally, I would calculate the LG CoG distance to the attachment point and move it along the rotation axis. But this information might be useful to store in the cpacs dataset. Especially, a more detailed LG is used in which more movable elements are, then the CoG change is not only along the rotation axis. And if I am only interested in the CoG of retracted and extended LG and not to the whole LG kinematic etc. it might be make sense.

**Comment by MarAlder** [comment]
Thanks for pointing out this inconsistency, I suggest to implement this extension in CPACS 3.5.

![grafik](https://github.com/DLR-SL/CPACS/assets/43143741/75381066-bce5-455c-be07-2bc1982511aa)

I'll forward your questio to the Q&A board.

**Comment by MarAlder** [comment]
General agreement on the last stakeholder meeting; no further feedback here. So I will close this topic.
