### ISSUE TITLE
Definition of ducts

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#768]
I would like to announce that the TiGL development is currently fokusing on ducts (see https://github.com/DLR-SC/tigl/issues/881), i.e. fuselage-like bodies which are substracted from the aircraft fuselage and wings: 

![grafik](https://user-images.githubusercontent.com/43143741/162151876-23da5d20-2699-4a82-9146-394665121f2b.png)

The work is currently based on the following XSD extension (see [`duct` branch](https://github.com/DLR-SL/CPACS/blob/ducts/schema/cpacs_schema.xsd)):
![grafik](https://user-images.githubusercontent.com/43143741/162152281-55201ff6-e2a7-4922-8c50-48a0f347c557.png)

Everyone is invited to contribute to this effort with comments, ideas or identification of possible problems, either here or at  https://github.com/DLR-SC/tigl/issues/881.

**Comment by joergbrech** [comment]
@CLiersch @rmaierl @AntonReiswich @sdeinert I just wanted to tag you guys here.

**Comment by CLiersch** [comment]
The proposal of @joergbrech sounds as a good idea to me. Imagine two engines sharing a &lt;duct&gt; element.
Then, a &lt;ductAssembly&gt; can be made a continuous line of &lt;duct&gt; elements from intake to outlet for one engine, without specifying the double-used &lt;duct&gt; twice.

**Comment by joergbrech** [comment]
> The proposal of @joergbrech sounds as a good idea to me. Imagine two engines sharing a <duct> element.
Then, a <ductAssembly> can be made a continuous line of <duct> elements from intake to outlet for one engine, without specifying the double-used <duct> twice.

We changed the definition in #774 accordingly and used this as a basis for our implementation in TiGL.

**Comment by MarAlder** [comment]
Implemented
