### ISSUE TITLE
Extend sparPositionType by curvePoint choice

### ISSUE THREAD

**Issue by sdeinert** [DLR-SL/CPACS#795]
In order to simplify wing structural layout definitions where several spars end on the same straight boundary spar, it would be good to extend the spar position definition by an option to use a curve point definition as well:
```XML
    <xsd:complexType name="sparPositionType">
        <xsd:complexContent>
            <xsd:extension base="complexBaseType">
                <xsd:choice minOccurs="1" maxOccurs="1">
                  <xsd:element name="sparPositionRib" type="wingRibPointType"></xsd:element>
                  <xsd:element name="sparPositionEtaXsi" type="etaXsiPointType"></xsd:element>
                  <xsd:element name="sparPositionCurve" type="curvePointType"></xsd:element>
                </xsd:choice>
                <xsd:attribute name="uID" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
```
By adding `sparPositionCurve` to the choice spars can have positions on other existing spars without the requirement to have a common spar position in both spars. Thus no extra positions need to be defined and the referenced spar is not affected by other spars referencing it.

The same logic as for the rib definition with a curve point can be applied here.

An example is shown here:
Front spar: 3 positions (at root, kink and tip)
Aux. spar: 2 positions (at root and at front spar)
No extra spar position is required for the front spar at the intersection with the aux spar. Thus, it is guaranteed that the front spar stays straight between the root and kink position.

![sparAtSpar](https://user-images.githubusercontent.com/15669066/191985061-07d7f951-61be-498b-8d05-12d719b112f3.png)

**Comment by rmaierl** [comment]
Sounds good, thank you.
This can save a lot of time and effort.

**Comment by MarAlder** [comment]
Sounds good to me. Thanks!

@joergbrech: Any concerns from the TiGL side?

**Comment by joergbrech** [comment]
No, looks good to me!

**Comment by MarAlder** [comment]
General agreement on the last stakeholder meeting. So I will close this topic.
