### ISSUE TITLE
Weight & Balance: mPayload should be optional

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS#805]
`mPayload` in [`operationalCase`](https://www.cpacs.de/documentation/CPACS_3_4_0_Docs/html/8c3f9884-d0d7-8114-cbbb-a785ee3aef92.htm) should be optional, because it is part of a breakdown of the `mass` [1..1] element, like `mFuel` [0..1].

**Comment by rmaierl** [comment]
Very good, thank you.
